[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"


[project]
name = "pipetui"
version = "0.1.0"
description = "PipeTUI DevOps TUI"
dependencies = [
    "click",
    "sqlalchemy",
    "alembic",
    "fastapi",
    "uvicorn",
    "textual",
]


[project.scripts]
pipetui = "cli.main:main"

[tool.setuptools.packages.find]
include = [
    "cli*",
    "core*",
    "services*",
    "storage*",
    "plugins*",
    "pipetui_api*",
    "logs*",
    "utils*",
    "tui*",
]
